### ISSUE TITLE
Merlin Hotend - Heater cartridge

### ISSUE THREAD

**Issue by ghost** [toolson/Tantillus_R#1]
In the BOM, the Merlin hotend is listed with a 12V heating cartridge. The printer uses 24V electronics.
This is not mentioned in the documentation.
Is the Merlin compatible with cartridges from the e3d ecosystem for example?
How is this issue solved?
Thanks

edit:
In the config, I noticed max_pwm 64.
Is this the solution to this issue?

**Comment by toolson** [comment]
Max 64 is the solution ;)
